# Generated by Django 5.1.2 on 2025-01-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MOU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('parties', models.TextField(help_text='List of parties involved')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('document', models.FileField(upload_to='mou_documents/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired')], default='draft', max_length=20)),
            ],
        ),
    ]
