# Generated by Django 5.1.2 on 2025-01-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mou', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='mou',
            name='parties',
        ),
        migrations.RemoveField(
            model_name='mou',
            name='status',
        ),
        migrations.AddField(
            model_name='mou',
            name='mou_coordinator_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='mou',
            name='mou_coordinator_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='mou',
            name='mou_coordinator_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mou',
            name='payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mou',
            name='staff_coordinator_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='mou',
            name='staff_coordinator_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='mou',
            name='staff_coordinator_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mou',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='mou_documents/'),
        ),
        migrations.AddField(
            model_name='mou',
            name='departments',
            field=models.ManyToManyField(help_text='Select departments involved', to='mou.department'),
        ),
        migrations.AddField(
            model_name='mou',
            name='outcomes',
            field=models.ManyToManyField(help_text='Select outcomes of MOU', to='mou.outcome'),
        ),
    ]
