# Generated by Django 5.1.2 on 2025-01-05 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mou', '0002_department_outcome_remove_mou_parties_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='mou',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='mou',
            name='document',
        ),
        migrations.RemoveField(
            model_name='mou',
            name='payment',
        ),
        migrations.AddField(
            model_name='mou',
            name='department',
            field=models.ManyToManyField(to='mou.department'),
        ),
        migrations.AddField(
            model_name='mou',
            name='payment_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mou',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='mou_pdfs/'),
        ),
        migrations.AlterField(
            model_name='mou',
            name='mou_coordinator_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mou',
            name='mou_coordinator_mobile',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mou',
            name='mou_coordinator_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mou',
            name='outcomes',
            field=models.ManyToManyField(to='mou.outcome'),
        ),
        migrations.AlterField(
            model_name='mou',
            name='staff_coordinator_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mou',
            name='staff_coordinator_mobile',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mou',
            name='staff_coordinator_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mou',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='mou',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mous', to='mou.organization'),
        ),
    ]
