# Generated by Django 5.1.2 on 2025-01-05 12:36

import django.db.models.deletion
import django.db.models.query
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mou', '0003_organization_remove_mou_departments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mou',
            name='pdf_file',
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(default='Default Department', max_length=100),
        ),
        migrations.AlterField(
            model_name='mou',
            name='department',
            field=models.ManyToManyField(blank=True, default=(), to='mou.department'),
        ),
        migrations.AlterField(
            model_name='mou',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mou',
            name='mou_coordinator_email',
            field=models.EmailField(blank=True, default='coordinator@example.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mou',
            name='mou_coordinator_mobile',
            field=models.CharField(blank=True, default='0000000000', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mou',
            name='mou_coordinator_name',
            field=models.CharField(blank=True, default='John Doe', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mou',
            name='organization',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.CASCADE, to='mou.organization'),
        ),
        migrations.AlterField(
            model_name='mou',
            name='outcomes',
            field=models.ManyToManyField(blank=True, default=(), to='mou.outcome'),
        ),
        migrations.AlterField(
            model_name='mou',
            name='staff_coordinator_email',
            field=models.EmailField(blank=True, default='staff@example.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mou',
            name='staff_coordinator_mobile',
            field=models.CharField(blank=True, default='1111111111', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mou',
            name='staff_coordinator_name',
            field=models.CharField(blank=True, default='Jane Doe', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mou',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mou',
            name='title',
            field=models.CharField(default='Default MoU Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(default='Default Organization', max_length=100),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='name',
            field=models.CharField(default='Default Outcome', max_length=100),
        ),
    ]
