# Generated by Django 5.1.2 on 2025-01-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mou', '0005_remove_mou_organization_remove_mou_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mou',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='mou',
            name='outcomes',
        ),
        migrations.RemoveField(
            model_name='mou',
            name='payment',
        ),
        migrations.AddField(
            model_name='mou',
            name='department',
            field=models.CharField(choices=[('placement', 'Placement'), ('iv', 'Industrial Visit'), ('workshop', 'Workshop'), ('research', 'Research Collaboration'), ('internship', 'Internship')], default='placement', max_length=100),
        ),
        migrations.AddField(
            model_name='mou',
            name='outcome',
            field=models.CharField(choices=[('placement', 'Placement'), ('iv', 'Industrial Visit'), ('workshop', 'Workshop'), ('research', 'Research'), ('internship', 'Internship')], default='placement', max_length=100),
        ),
        migrations.AddField(
            model_name='mou',
            name='payment_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mou',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='mou',
            name='mou_coordinator_email',
            field=models.EmailField(default='noemail@domain.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='mou',
            name='mou_coordinator_mobile',
            field=models.CharField(default='0987654321', max_length=15),
        ),
        migrations.AlterField(
            model_name='mou',
            name='mou_coordinator_name',
            field=models.CharField(default='temp_name', max_length=100),
        ),
        migrations.AlterField(
            model_name='mou',
            name='staff_coordinator_email',
            field=models.EmailField(default='noemail@domain.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='mou',
            name='staff_coordinator_mobile',
            field=models.CharField(default='0987654321', max_length=15),
        ),
        migrations.AlterField(
            model_name='mou',
            name='staff_coordinator_name',
            field=models.CharField(default='temp_name', max_length=100),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Outcome',
        ),
    ]
