# Generated by Django 5.1.2 on 2025-01-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mou', '0006_remove_mou_departments_remove_mou_outcomes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mou',
            name='department',
            field=models.CharField(choices=[('cse', 'Computer Science and Engineering'), ('it', 'Information Technology'), ('ece', 'Electronics and Communication Engineering'), ('mech', 'Mechanical Engineering'), ('civil', 'Civil Engineering')], max_length=100),
        ),
        migrations.AlterField(
            model_name='mou',
            name='mou_coordinator_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mou',
            name='mou_coordinator_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mou',
            name='mou_coordinator_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mou',
            name='outcome',
            field=models.CharField(choices=[('placement', 'Placement'), ('iv', 'Industrial Visit'), ('workshop', 'Workshop'), ('research', 'Research Collaboration'), ('internship', 'Internship')], max_length=100),
        ),
        migrations.AlterField(
            model_name='mou',
            name='payment_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mou',
            name='staff_coordinator_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mou',
            name='staff_coordinator_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mou',
            name='staff_coordinator_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
