# Generated by Django 5.1.2 on 2025-01-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mou', '0008_department_outcome_remove_mou_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mou',
            name='outcome',
        ),
        migrations.AddField(
            model_name='mou',
            name='outcome',
            field=models.ManyToManyField(related_name='mous', to='mou.outcome'),
        ),
    ]
