# Generated by Django 5.1.2 on 2025-01-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mou', '0009_remove_mou_outcome_mou_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mou',
            name='payment_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
