# Generated by Django 5.1.2 on 2025-01-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mou', '0010_alter_mou_payment_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mou',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
